### ISSUE TITLE
Error when executing the command 'pip install -r requirements.txt'

### ISSUE THREAD

**Issue by Chairy-neko** [3DTopia/ThemeStation#3]
Some packages do not have a specified version (gradio, matplotlib, etc.), and conflicts and errors frequently occur during installation. Can the requirements.txt file provide more specific non-conflicting versions?

**Comment by zhenwwang** [comment]
@Chairy-neko Hi. It should work with most versions and works well on my machine. If you find an incompatible version, you can report it as a bug! BTW, have you created a new conda environment with python==3.10 and without torch installed? We have specified the torch version in requirements.txt.
