### ISSUE TITLE
config of prompt processor seems to be wrong

### ISSUE THREAD

**Issue by hey0chen** [3DTopia/ThemeStation#5]
Hi, I tried to run code but failed. I noticed that the config of prompt processor seems to be wrong. Following the theme-station-render.yaml, the coding will run with run to
`
            self.ref_prompt_processor = threestudio.find(
                self.cfg.prompt_processor_type
            )(self.cfg.ref_prompt_processor)
`
but the cfg.ref_prompt_processor is empty.

**Comment by zhenwwang** [comment]
@hey0chen Hi, we wrongly set  `use_reference_model_dreambooth=True` in `config/theme-station-render.yaml (L28)`. Please set this option to False and try again.

**Comment by hey0chen** [comment]
> @hey0chen Hi, we wrongly set `use_reference_model_dreambooth=True` in `config/theme-station-render.yaml (L28)`. Please set this option to False and try again.

@zhenwwang Thanks for reply, the code was already to run at this stage, but got a new problem. Can you check the parameters of `theme-station-optimization.yaml`? I got the similar error when I run `sh scripts/run_optimization.sh`

**Comment by zhenwwang** [comment]
@hey0chen Hi, could you please provide the error message for reference? I cannot reproduce this error on my site.

**Comment by hey0chen** [comment]
> @hey0chen Hi, could you please provide the error message for reference? I cannot reproduce this error on my site.

Sorry, I found the reason of this erro, it was caused by failing to download online model of huggingface. Thank you for your reply!
