### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by muses0229** [3DTopia/ThemeStation#6]

**Comment by yejr0229** [comment]
Also I'd like to know the main application of ThemeStation. In my opinion, given a textured mesh, ThemeStation generates a refined mesh with more detailed texture, is that correct? And how much time will it take?

**Comment by zhenwwang** [comment]
@yejr0229 Hi, our experiments are conducted on a single A100 GPU, 3090 with 24GB is not sufficient for our current version. 
- For the application of ThemeStation, our main objective is to generate theme-consistent variations of given 3D exemplars. It can also be used to generate a refined mesh with detailed texture if your input is a textured mesh. 
- As our current approach is optimization-based, it may take about 1~2 hours based on how many optimization steps you choose.
- We are now designing another method with similar applications to ThemeStation, but with less GPU usage (can run on a GPU with 24GB or less) and faster time-consuming (less than 10 seconds). We will release the new model within these two months. You can follow my github/homepage for updates.

**Comment by hey0chen** [comment]
> @yejr0229 Hi, our experiments are conducted on a single A100 GPU, 3090 with 24GB is not sufficient for our current version.
> 
> * For the application of ThemeStation, our main objective is to generate theme-consistent variations of given 3D exemplars. It can also be used to generate a refined mesh with detailed texture if your input is a textured mesh.
> * As our current approach is optimization-based, it may take about 1~2 hours based on how many optimization steps you choose.
> * We are now designing another method with similar applications to ThemeStation, but with less GPU usage (can run on a GPU with 24GB or less) and faster time-consuming (less than 10 seconds). We will release the new model within these two months. You can follow my github/homepage for updates.

@zhenwwang Hi, I tried to run the code on a single A6000 GPU with 48GB VRM but still out of memory. Can you provide some suggestions for this?

**Comment by zhenwwang** [comment]
> > @yejr0229 Hi, our experiments are conducted on a single A100 GPU, 3090 with 24GB is not sufficient for our current version.
> > 
> > * For the application of ThemeStation, our main objective is to generate theme-consistent variations of given 3D exemplars. It can also be used to generate a refined mesh with detailed texture if your input is a textured mesh.
> > * As our current approach is optimization-based, it may take about 1~2 hours based on how many optimization steps you choose.
> > * We are now designing another method with similar applications to ThemeStation, but with less GPU usage (can run on a GPU with 24GB or less) and faster time-consuming (less than 10 seconds). We will release the new model within these two months. You can follow my github/homepage for updates.
> 
> @zhenwwang Hi, I tried to run the code on a single A6000 GPU with 48GB VRM but still out of memory. Can you provide some suggestions for this?

Hi, you may need an A100 GPU with 80GB. We are now working on another project (https://rag-3d.github.io/), which supports fast theme-aware 3D-to-3D generation and requires much less GPU memory. Code will be released once our paper is accepted.
