### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by xzr52** [3DTopia/ThemeStation#7]
That's a great work. I am particularly interested in the datasets used for testing in your research. Could you please let me know if you have any plans to make these datasets publicly available?

**Comment by zhenwwang** [comment]
> That's a great work. I am particularly interested in the datasets used for testing in your research. Could you please let me know if you have any plans to make these datasets publicly available?

@xzr52 Hi, generally, all the 3D models we used could be found online. As described in our paper (Sec. 4.1.1), we use 3D models downloaded from Sketchfab (https://sketchfab.com/) and exported from Microsoft 3D Viewer (an app in Windows App Store).
